### ISSUE TITLE
[taiga-backend] "django.db.backends.postgresql_psycopg2" in settings/local.py

### ISSUE THREAD

**Issue by ClashTheBunny** [ipedrazas/taiga-docker#18]
According to taigaio/taiga-back#272, `django.db.backends.postgresql_psycopg2` needs to be `transaction_hooks.backends.postgresql_psycopg2` in local.py.  The stable branch is up to date as of commit taigaio/taiga-back@d98455744943f88717f116bd1c1331bef63cc802.

A simple rebuild and push to docker hub would possibly solve this (if it doesn't introduce more errors).

I may give it a shot myself.  As it stands, taiga doesn't create any new items because of it:
```bash
Request repr():
<WSGIRequest
path:/api/v1/userstories,
GET:<QueryDict: {}>,
POST:<could not parse>,
COOKIES:{},
META:{'API_NAME': 'runt.local',
 'CONTENT_LENGTH': '338',
 'CONTENT_TYPE': 'application/json',
 'DEBIAN_FRONTEND': 'noninteractive',
 'DJANGO_SETTINGS_MODULE': 'settings',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HOME': '/root',
 'HOSTNAME': 'd4a6a0f10d25',
 'HTTP_ACCEPT': 'application/json, text/plain, */*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en',
 'HTTP_AUTHORIZATION': 'Bearer '
                       'eyJ1c2VyX2F1dGhlbnRpY2F0aW9uX2lkIjo0fQ:1ZcgpI:WnZpOMloCH7Iw90Th34jAsBJCc4',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'runt.local:8000',
 'HTTP_ORIGIN': 'http://runt.local',
 'HTTP_REFERER': 'http://runt.local/project/admin-ipip-neo/kanban',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/45.0.2454.93 Safari/537.36',
 'HTTP_X_SESSION_ID': 'd351fe19875fb543214102b800300e1f3b73106a',
 'LANG': 'en_US.UTF-8',
 'LC_TYPE': 'en_US.UTF-8',
 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'PATH_INFO': '/api/v1/userstories',
 'POSTGRES_ENV_LANG': 'en_US.utf8',
 'POSTGRES_ENV_PGDATA': '/var/lib/postgresql/data',
 'POSTGRES_ENV_PG_MAJOR': '9.4',
 'POSTGRES_ENV_PG_VERSION': '9.4.4-1.pgdg80+1',
 'POSTGRES_NAME': '/taiga-back/postgres',
 'POSTGRES_PORT': 'tcp://172.17.0.13:5432',
 'POSTGRES_PORT_5432_TCP': 'tcp://172.17.0.13:5432',
 'POSTGRES_PORT_5432_TCP_ADDR': '172.17.0.13',
 'POSTGRES_PORT_5432_TCP_PORT': '5432',
 'POSTGRES_PORT_5432_TCP_PROTO': 'tcp',
 'PYTHON_PIP_VERSION': '7.1.0',
 'PYTHON_VERSION': '3.4.3',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.148',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'POST',
 'RUN_MAIN': 'true',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'd4a6a0f10d25',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'TZ': 'UTC',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
-------------------------------------------------------------------------------
[18/Sep/2015 11:10:42] "POST /api/v1/userstories HTTP/1.1" 500 37
ERROR:2015-09-18 11:11:08,649: Internal Server Error: /api/v1/userstories
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/taiga/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/taiga/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/taiga/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/taiga/taiga/projects/userstories/api.py", line 172, in create
    response = super().create(*args, **kwargs)
  File "/taiga/taiga/base/api/mixins.py", line 72, in create
    self.object = serializer.save(force_insert=True)
  File "/taiga/taiga/base/api/serializers.py", line 1055, in save
    self.object = super().save(**kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 614, in save
    self.save_object(self.object, **kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 1073, in save_object
    obj.save(**kwargs)
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/projects/references/models.py", line 92, in attach_sequence
    instance.save(update_fields=['ref'])
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/events/signal_handlers.py", line 43, in on_save_any_model
    connection.on_commit(emit_event)
  File "/usr/local/lib/python3.4/site-packages/django/db/__init__.py", line 40, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'
```

```json
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "startedDateTime": "2015-09-18T11:11:06.820Z",
        "time": 2606.94599999988,
        "request": {
          "method": "POST",
          "url": "http://runt.local:8000/api/v1/userstories",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Authorization",
              "value": "Bearer eyJ1c2VyX2F1dGhlbnRpY2F0aW9uX2lkIjo0fQ:1ZcgpI:WnZpOMloCH7Iw90Th34jAsBJCc4"
            },
            {
              "name": "Origin",
              "value": "http://runt.local"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Host",
              "value": "runt.local:8000"
            },
            {
              "name": "Accept-Language",
              "value": "en"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "X-Session-Id",
              "value": "d351fe19875fb543214102b800300e1f3b73106a"
            },
            {
              "name": "Referer",
              "value": "http://runt.local/project/admin-ipip-neo/kanban"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "338"
            },
            {
              "name": "DNT",
              "value": "1"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 613,
          "bodySize": 338,
          "postData": {
            "mimeType": "application/json",
            "text": "{\"_attrs\":{\"project\":1,\"points\":{},\"status\":1,\"is_archived\":false,\"tags\":[]},\"_name\":\"userstories\",\"_dataTypes\":{},\"_modifiedAttrs\":{\"points\":{\"1\":2,\"2\":2,\"3\":5,\"4\":2}},\"_isModified\":true,\"project\":1,\"points\":{\"1\":2,\"2\":2,\"3\":5,\"4\":2},\"status\":1,\"is_archived\":false,\"tags\":[],\"subject\":\"asdf\",\"description\":\"asdf\",\"team_requirement\":true}"
          }
        },
        "response": {
          "status": 500,
          "statusText": "INTERNAL SERVER ERROR",
          "httpVersion": "HTTP/1.0",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 18 Sep 2015 11:11:08 GMT"
            },
            {
              "name": "Vary",
              "value": "Cookie, Accept-Language"
            },
            {
              "name": "Server",
              "value": "WSGIServer/0.2 CPython/3.4.3"
            },
            {
              "name": "Content-Language",
              "value": "en"
            },
            {
              "name": "Access-Control-Max-Age",
              "value": "3600"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "POST,GET,OPTIONS,PUT,DELETE,PATCH,HEAD"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=utf-8"
            },
            {
              "name": "Access-Control-Allow-Origin",
              "value": "*"
            },
            {
              "name": "Access-Control-Expose-Headers",
              "value": "x-pagination-count,x-paginated,x-paginated-by,x-pagination-current,x-pagination-next,x-pagination-prev,x-site-host,x-site-register"
            },
            {
              "name": "Access-Control-Allow-Credentials",
              "value": "true"
            },
            {
              "name": "Access-Control-Allow-Headers",
              "value": "content-type,x-requested-with,authorization,accept-encoding,x-disable-pagination,x-host,x-session-id"
            }
          ],
          "cookies": [],
          "content": {
            "size": 37,
            "mimeType": "text/html",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 673,
          "bodySize": 37,
          "_transferSize": 710
        },
        "cache": {},
        "timings": {
          "blocked": 4.1180000116583,
          "dns": 860.9729999880077,
          "connect": 980.4920000024141,
          "send": 0.16000001050997525,
          "wait": 759.29199998791,
          "receive": 1.9109999993797828,
          "ssl": -1
        },
        "connection": "267976"
      }
    ]
  }
}
```

**Comment by ClashTheBunny** [comment]
To get this working, a simple sed from the docker host works:
```bash
docker exec -it taiga-back bash -c "sed -i -e 's/django.db.backends.postgresql_psycopg2/transaction_hooks.backends.postgresql_psycopg2/g' settings/local.py"
```

**Comment by ipedrazas** [comment]
Thanks for the comment,
I've added the `sed` to the build script. I'll rebuild and re-test and re-port :smile_cat:

**Comment by ipedrazas** [comment]
you could have sent a PR too :wink:  (I know that you cannot update my docker images, I really appreciate your effort and help)

**Comment by pkoretic** [comment]
Any progress on this? Latest image still has this issues.
Is docker image just made for preview?

**Comment by ipedrazas** [comment]
which issues?

**Comment by pkoretic** [comment]
issue, sorry
docker logs show this failure when trying to open new task in taiga, 
setting django.db.backends.postgresql_psycopg2 to transaction_hooks.backends.postgresql_psycopg2 fixes it
