### ISSUE TITLE
{"error": "Server application error"}

### ISSUE THREAD

**Issue by randinfo** [ipedrazas/taiga-docker#42]
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [Django] ERROR (EXTERNAL IP): Internal Server Error:
 /api/v1/userstories
From: root@localhost
[04/Dec/2016 12:42:13] "POST /api/v1/userstories HTTP/1.1" 500 37
To: example@example.com
Date: Sun, 04 Dec 2016 12:42:19 -0000
Message-ID: <20161204124219.10.6459@78490dd9209b>

Internal Server Error: /api/v1/userstories
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/taiga/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/taiga/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/taiga/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/taiga/taiga/projects/userstories/api.py", line 172, in create
    response = super().create(*args, **kwargs)
  File "/taiga/taiga/base/api/mixins.py", line 72, in create
    self.object = serializer.save(force_insert=True)
  File "/taiga/taiga/base/api/serializers.py", line 1055, in save
    self.object = super().save(**kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 614, in save
    self.save_object(self.object, **kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 1073, in save_object
    obj.save(**kwargs)
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/projects/references/models.py", line 92, in attach_sequence
    instance.save(update_fields=['ref'])
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/events/signal_handlers.py", line 43, in on_save_any_model
    connection.on_commit(emit_event)
  File "/usr/local/lib/python3.4/site-packages/django/db/__init__.py", line 40, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'

Request repr():
<WSGIRequest
path:/api/v1/userstories,
GET:<QueryDict: {}>,
POST:<could not parse>,
COOKIES:{},
META:{'API_NAME': 'board.lmka.me',
 'CONTENT_LENGTH': '237',
 'CONTENT_TYPE': 'application/json',
 'DEBIAN_FRONTEND': 'noninteractive',
 'DJANGO_SETTINGS_MODULE': 'settings',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HOME': '/root',
 'HOSTNAME': '78490dd9209b',
[04/Dec/2016 12:42:18] "OPTIONS /api/v1/userstories HTTP/1.1" 200 0
ERROR:2016-12-04 12:42:19,151: Internal Server Error: /api/v1/userstories
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/taiga/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/taiga/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/taiga/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/taiga/taiga/projects/userstories/api.py", line 172, in create
    response = super().create(*args, **kwargs)
  File "/taiga/taiga/base/api/mixins.py", line 72, in create
    self.object = serializer.save(force_insert=True)
  File "/taiga/taiga/base/api/serializers.py", line 1055, in save
    self.object = super().save(**kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 614, in save
    self.save_object(self.object, **kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 1073, in save_object
    obj.save(**kwargs)
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/projects/references/models.py", line 92, in attach_sequence
    instance.save(update_fields=['ref'])
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/events/signal_handlers.py", line 43, in on_save_any_model
    connection.on_commit(emit_event)
  File "/usr/local/lib/python3.4/site-packages/django/db/__init__.py", line 40, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'
 'HTTP_ACCEPT': 'application/json, text/plain, */*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fr',
 'HTTP_AUTHORIZATION': 'Bearer '
                       'eyJ1c2VyX2F1dGhlbnRpY2F0aW9uX2lkIjo0fQ:1cDW5e:-RiI2DOGxEqh8MRH1TewHj0ytis',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': 'board.lmka.me:8000',
 'HTTP_ORIGIN': 'http://board.lmka.me',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_REFERER': 'http://board.lmka.me/project/amar-scred-news/kanban',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 '
                    '(KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36',
 'HTTP_X_SESSION_ID': '2e873bd8c4cfe0a51ceb05a763aff02a7afac05c',
 'LANG': 'en_US.UTF-8',
 'LC_TYPE': 'en_US.UTF-8',
 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'PATH_INFO': '/api/v1/userstories',
 'POSTGRES_ENV_GOSU_VERSION': '1.7',
 'POSTGRES_ENV_LANG': 'en_US.utf8',
 'POSTGRES_ENV_PGDATA': '/var/lib/postgresql/data',
 'POSTGRES_ENV_PG_MAJOR': '9.6',
 'POSTGRES_ENV_PG_VERSION': '9.6.1-1.pgdg80+1',
 'POSTGRES_NAME': '/taiga-back/postgres',
 'POSTGRES_PORT': 'tcp://172.17.0.2:5432',
 'POSTGRES_PORT_5432_TCP': 'tcp://172.17.0.2:5432',
 'POSTGRES_PORT_5432_TCP_ADDR': '172.17.0.2',
 'POSTGRES_PORT_5432_TCP_PORT': '5432',
 'POSTGRES_PORT_5432_TCP_PROTO': 'tcp',
 'PYTHON_PIP_VERSION': '7.1.0',
 'PYTHON_VERSION': '3.4.3',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '86.219.230.124',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'POST',
 'RUN_MAIN': 'true',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '78490dd9209b',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'TZ': 'UTC',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=7>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by steimntz** [comment]
The pull request #43 fixes it.

**Comment by port22** [comment]
Guys, I still have this issue when I want to create a new user story in a kanban for example, is that the same problem? Of course I use the current version.

`ERROR:2017-01-24 13:21:08,535: Internal Server Error: /api/v1/userstories
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/taiga/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/taiga/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/taiga/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/taiga/taiga/projects/userstories/api.py", line 172, in create
    response = super().create(*args, **kwargs)
  File "/taiga/taiga/base/api/mixins.py", line 72, in create
    self.object = serializer.save(force_insert=True)
  File "/taiga/taiga/base/api/serializers.py", line 1055, in save
    self.object = super().save(**kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 614, in save
    self.save_object(self.object, **kwargs)
  File "/taiga/taiga/base/api/serializers.py", line 1073, in save_object
    obj.save(**kwargs)
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/projects/references/models.py", line 92, in attach_sequence
    instance.save(update_fields=['ref'])
  File "/taiga/taiga/projects/userstories/models.py", line 118, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/taiga/taiga/events/signal_handlers.py", line 43, in on_save_any_model
    connection.on_commit(emit_event)
  File "/usr/local/lib/python3.4/site-packages/django/db/__init__.py", line 40, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Subject: [Django] ERROR (EXTERNAL IP): Internal Server Error:
 /api/v1/userstories`

**Comment by bluefalcon26** [comment]
@port22 The issue is fixed in code, but the it seems the docker repository doesn't reflect this change yet. You can edit settings/local.py on taiga-back manually and change line 33.

**Comment by ezsper** [comment]
I'm getting the Server application error, but on the taiga-back container I couldn't find a log file to check for any errors. Where should I be looking at?

Obs.: I was able to login with admin, I was able to create projects, but as it gives the error above I need to refresh it to see the changes. The error is happening after the database persistence on the API.
